### ISSUE TITLE
Running a 5090 and getting OOM errors on 720p resolution

### ISSUE THREAD

**Issue by MrEdwards007** [thu-ml/TurboDiffusion#52]
I tried export PYTORCH_ALLOC_CONF=expandable_segments:True to see if that would resolve the OOM errors on my 5090 but it does not.
I've been at this for hours and havent been able to determine the right combination to use and not get OOM

I am **also** utilizing the "--quant_linear" argument

```
export PYTHONPATH=turbodiffusion
export PYTORCH_ALLOC_CONF=expandable_segments:True
export TOKENIZERS_PARALLELISM=false

python turbodiffusion/inference/wan2.1_t2v_infer.py \
    --model Wan2.1-14B \
    --dit_path checkpoints/TurboWan2.1-T2V-14B-720P-quant.pth \
    --prompt "A photo realistic stylish woman walks down a Tokyo street filled with warm glowing neon and animated city signage. She wears a black leather jacket, a long red dress, and black boots, and carries a black purse. She wears sunglasses and red lipstick. She walks confidently and casually. The street is damp and reflective, creating a mirror effect of the colorful lights. Many pedestrians walk about." \
    --resolution 720p \
    --aspect_ratio 16:9 \
    --num_steps 4 \
    --seed 297308 \
    --attention_type sagesla \
    --sla_topk 0.15 \
    --num_samples 1 \
    --num_frames 77 \
    --sigma_max 80 \
    --save_path /home/wedwards/Documents/turbo_diffusion_ouput/t2v_20251226_104112.mp4 \
    --quant_linear
```

Console Information
.
.
.

[12-26 10:48:47|INFO|turbodiffusion/inference/wan2.1_t2v_infer.py:61:<module>] Computing embedding for prompt: A photo realistic stylish woman walks down a Tokyo street filled with warm glowing neon and animated city signage. She wears a black leather jacket, a long red dress, and black boots, and carries a black purse. She wears sunglasses and red lipstick. She walks confidently and casually. The street is damp and reflective, creating a mirror effect of the colorful lights. Many pedestrians walk about.
[12-26 10:48:47|INFO|turbodiffusion/rcm/utils/umt5.py:495:__init__] loading checkpoints/models_t5_umt5-xxl-enc-bf16.pth
[12-26 10:48:57|INFO|turbodiffusion/inference/wan2.1_t2v_infer.py:66:<module>] Loading DiT model from checkpoints/TurboWan2.1-T2V-14B-720P-quant.pth
[12-26 10:48:57|INFO|turbodiffusion/rcm/networks/wan2pt1.py:829:enable_selective_checkpoint] Enable selective checkpoint with mm_only, for every 1 blocks. Total blocks: 40
[12-26 10:49:13|SUCCESS|turbodiffusion/inference/wan2.1_t2v_infer.py:69:<module>] Successfully loaded DiT model.
[12-26 10:49:13|INFO|turbodiffusion/rcm/tokenizers/wan2pt1.py:590:_video_vae] loading checkpoints/Wan2.1_VAE.pth
[12-26 10:49:13|INFO|turbodiffusion/inference/wan2.1_t2v_infer.py:75:<module>] Generating with prompt: A photo realistic stylish woman walks down a Tokyo street filled with warm glowing neon and animated city signage. She wears a black leather jacket, a long red dress, and black boots, and carries a black purse. She wears sunglasses and red lipstick. She walks confidently and casually. The street is damp and reflective, creating a mirror effect of the colorful lights. Many pedestrians walk about.
Sampling: 100%|█████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:32<00:00,  8.11s/it]
Traceback (most recent call last):
  File "/home/wedwards/Documents/Programs/TurboDiffusion/turbodiffusion/inference/wan2.1_t2v_infer.py", line 132, in <module>
    video = tokenizer.decode(samples)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wedwards/Documents/Programs/TurboDiffusion/turbodiffusion/rcm/tokenizers/wan2pt1.py", line 737, in decode
    return self.model.decode(
           ^^^^^^^^^^^^^^^^^^
  File "/home/wedwards/anaconda3/envs/turbodiffusion/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wedwards/Documents/Programs/TurboDiffusion/turbodiffusion/rcm/tokenizers/wan2pt1.py", line 685, in decode
    video_recon = self.model.decode(zs, self.scale)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wedwards/Documents/Programs/TurboDiffusion/turbodiffusion/rcm/tokenizers/wan2pt1.py", line 532, in decode
    out_ = self.decoder(x[:, :, i : i + 1, :, :], feat_cache=self._feat_map, feat_idx=self._conv_idx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wedwards/anaconda3/envs/turbodiffusion/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wedwards/anaconda3/envs/turbodiffusion/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wedwards/Documents/Programs/TurboDiffusion/turbodiffusion/rcm/tokenizers/wan2pt1.py", line 416, in forward
    x = layer(x, feat_cache, feat_idx)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wedwards/anaconda3/envs/turbodiffusion/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wedwards/anaconda3/envs/turbodiffusion/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wedwards/Documents/Programs/TurboDiffusion/turbodiffusion/rcm/tokenizers/wan2pt1.py", line 202, in forward
    x = layer(x, feat_cache[idx])
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wedwards/anaconda3/envs/turbodiffusion/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wedwards/anaconda3/envs/turbodiffusion/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wedwards/Documents/Programs/TurboDiffusion/turbodiffusion/rcm/tokenizers/wan2pt1.py", line 55, in forward
    return super().forward(x)
           ^^^^^^^^^^^^^^^^^^
  File "/home/wedwards/anaconda3/envs/turbodiffusion/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 717, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wedwards/anaconda3/envs/turbodiffusion/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 712, in _conv_forward
    return F.conv3d(
           ^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 17.80 GiB. GPU 0 has a total capacity of 31.35 GiB of which 2.64 GiB is free. Including non-PyTorch memory, this process has 27.65 GiB memory in use. Of the allocated memory 7.80 GiB is allocated by PyTorch, and 19.26 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
(turbodiffusion) wedwards@Inf-Imagine-Linux:~/Documents/Programs/TurboDiffusion$

**Comment by johndpope** [comment]
im in same boat - https://github.com/thu-ml/TurboDiffusion/pull/53
i create this after some troubleshooting - 
this installs it properly (though targeting cuda13 + nightly pytorch) - im yet to confirm it works.

<img width="847" height="421" alt="Image" src="https://github.com/user-attachments/assets/2148b8f8-f838-479a-a5a5-dbbaccf75cf1" />

**Comment by jt-zhang** [comment]
Try to use `torch==2.8.0`

**Comment by johndpope** [comment]
2.8 doesnt work with cuda 13. 
i have it working with cuda 13 + pytorch nightly
the problem with above is 81 frames  - take it down to 49 frames.

**Comment by jt-zhang** [comment]
see #42

**Comment by MrEdwards007** [comment]
> im in same boat - [#53](https://github.com/thu-ml/TurboDiffusion/pull/53) i create this after some troubleshooting - this installs it properly (though targeting cuda13 + nightly pytorch) - im yet to confirm it works.
> <img alt="Image" width="847" height="421" src="https://private-user-images.githubusercontent.com/289994/530428068-2148b8f8-f838-479a-a5a5-dbbaccf75cf1.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY4MTE0MjgsIm5iZiI6MTc2NjgxMTEyOCwicGF0aCI6Ii8yODk5OTQvNTMwNDI4MDY4LTIxNDhiOGY4LWY4MzgtNDc5YS1hNWE1LWRiYmFjY2Y3NWNmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIyN1QwNDUyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWI2MTZkMjUwZTZjODdkNzY1N2MxN2MzZWQxYzc0YWU4ZTBlOTcyOTVjNDNiZGQzODcxZTA5YTExZmIwNGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zYGkpDJbAcQ4nHrE5J5jTejM_lTpMO-F5yazT-b0A7o">
> 
> I got it working i2v - check install.sh - have to get spargeattn with blackwell support.

@johndpope...These *may* help
https://github.com/thu-ml/TurboDiffusion/issues/54#issue-3764296343
https://github.com/thu-ml/TurboDiffusion/issues/55#issue-3764302076

I'm hoping to understand your pull request so I can try out your program alongside of my own
https://github.com/thu-ml/TurboDiffusion/issues/56#issue-3764350016

**Comment by MrEdwards007** [comment]
@johndpope, I dont know how the development team got this to work on a 5090 at 720p.  Ive tried multiple strategies, memory dumping between stages,  tiling (attempted), taking it down to 32 frames and I also used your technique for caching the prompts.  

I'm tracking every point along the way and at one point, I'm just 800MB short of being able to fit this onto gpu before I get OOM.

The only way that I've been able to make this work at 720p is to offload to cpu, (which takes forever) but that **completely defeated the purpose** as it made the entire process 21 minutes to generate 5 seconds of video.

**Comment by whx1003** [comment]
> [@johndpope](https://github.com/johndpope), I dont know how the development team got this to work on a 5090 at 720p. Ive tried multiple strategies, memory dumping between stages, tiling (attempted), taking it down to 32 frames and I also used your technique for caching the prompts.
> 
> I'm tracking every point along the way and at one point, I'm just 800MB short of being able to fit this onto gpu before I get OOM.
> 
> The only way that I've been able to make this work at 720p is to offload to cpu, (which takes forever) but that **completely defeated the purpose** as it made the entire process 21 minutes to generate 5 seconds of video.

During our tests, we ran into the same OOM issue with Torch 2.9. Using `torch==2.8.0` fixed it, which is why the README recommends that version.

**Comment by MrEdwards007** [comment]
@johndpope, using your cache_t5.py as a foundation for a workflow, I have made optimizations, resulting in a pull request
https://github.com/thu-ml/TurboDiffusion/pull/73

It take a lot more effort to run OOM and it runs faster.

**Comment by phongtrannm** [comment]
## WSL2 OOM / Freeze Fix (what I had → what broke → what I changed → results)

I’m running TurboDiffusion on **WSL2** and kept hitting **OOM / instability** when executing multiple jobs back-to-back. My WSL2 memory setup is:

**File:** `C:\Users\Admin\.wslconfig`

```ini
[wsl2]
memory=50GB
swap=32GB
swapfile=Z:\\wsl\\swap.vhdx
```

Runtime environment (example):

* WSL2 Linux `6.6.87.2`
* Python `3.12.3`
* PyTorch `2.8.0+cu128`, CUDA `12.8` (CUDA available)
* `flash_attn 2.8.3`, `spas_sage_attn 0.1.0`
* RAM ~`49 GiB`, swap `32 GiB`, VRAM ~`31.84 GiB` (1 GPU)

### What I tried first (not enough)

Initially I only did the “standard” cleanup after each job:

* `gc.collect()`
* `torch.cuda.empty_cache()` (and related CUDA cache cleanup)

This helped **VRAM** drop, but **system RAM kept growing** over time. After **2 consecutive jobs**, I could reproduce errors, and sometimes **WSL2 would crash/die** completely. The key point: **VRAM cleanup ≠ RAM cleanup**. Even if CUDA cache is cleared, CPU heap memory can stay bloated and keep pushing WSL toward swap pressure and failure.

### What actually fixed it

I added a second layer of cleanup: **explicitly releasing system RAM after every job**, not just CUDA/torch cleanup. I also made a few stability-oriented choices:

* Enable `malloc_trim` (return freed heap memory back to the OS after each job)
* Preload two I2V models (high/low) on CPU at startup (reduce runtime I/O spikes)
* Do **not** preload the T5 encoder; load it per job (this reduced long-run hangs/OOM for my setup)

### Results after the fix (stable behavior)

After adding RAM cleanup per job, things became much more stable:

* **Swap stayed low** around **~2.5 / 32 GiB**, and even **decreased to ~2.3 GiB** near the end (instead of growing toward full swap like before).
* **RAM stayed ~23–30 GiB while running**, then **dropped back after cleanup** (no longer creeping close to 49 GiB).
* **VRAM behaved as expected**: it increases during sampling, then drops back to a small baseline (about **~0.6 GiB reserved**).

### Log proof (what the cleanup shows)

Below is a concrete example where CUDA cleanup successfully reduces **VRAM reserved**, but RAM only drops after full cleanup:

```text
[SYS]  after_sampling: cpu=5.3% ram=33.81/49.01 GiB
[VRAM] after_sampling: allocated=0.31 GiB reserved=0.51 GiB
[MONITOR] cpu=5.4% ram=33.82/49.01 GiB swap=2.93/32.00 GiB ... vram_alloc=2.35 vram_resv=5.30
...
Cleanup: GC and CUDA cache cleanup.

[SYS]  before_gc: cpu=11.5% ram=34.18/49.01 GiB
[VRAM] before_gc: allocated=0.43 GiB reserved=6.01 GiB

[SYS]  after_gc: cpu=5.1% ram=34.18/49.01 GiB
[VRAM] after_gc: allocated=0.43 GiB reserved=6.01 GiB

[SYS]  after_cuda_empty_cache: cpu=0.6% ram=34.18/49.01 GiB
[VRAM] after_cuda_empty_cache: allocated=0.43 GiB reserved=0.69 GiB

[MONITOR] cpu=5.1% ram=31.67/49.01 GiB swap=2.93/32.00 GiB ... vram_alloc=0.01 vram_resv=0.69
```

**Takeaway:** if you’re running repeated inference jobs on WSL2, clearing CUDA cache alone may look “successful” (VRAM drops) but still fails in the next job because **RAM keeps accumulating**. The practical fix is to **clean both VRAM and RAM after each job**, and monitor `ram/swap/vram` deltas (especially after `after_gc` and `after_cuda_empty_cache`) to confirm memory actually comes down.
