### ISSUE TITLE
OOM on 24GB GPU (like RTX 4090) on umt5 loading

### ISSUE THREAD

**Issue by gnattu** [thu-ml/TurboDiffusion#6]
```
Traceback (most recent call last):
  File "/src/TurboDiffusion/turbodiffusion/inference/wan2.2_i2v_infer.py", line 69, in <module>
    text_emb = get_umt5_embedding(checkpoint_path=args.text_encoder_path, prompts=args.prompt).to(**tensor_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/TurboDiffusion/turbodiffusion/rcm/utils/umt5.py", line 534, in get_umt5_embedding
    t5_encoder = UMT5EncoderModel(text_len=max_length, device=device, checkpoint_path=checkpoint_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/TurboDiffusion/turbodiffusion/rcm/utils/umt5.py", line 494, in __init__
    model = umt5_xxl(encoder_only=True, dtype=dtype, device=device).eval().requires_grad_(False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/TurboDiffusion/turbodiffusion/rcm/utils/umt5.py", line 465, in umt5_xxl
    return _t5("umt5-xxl", **cfg)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/src/TurboDiffusion/turbodiffusion/rcm/utils/umt5.py", line 446, in _t5
    model = model.to(dtype=dtype, device=device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/TurboDiffusion/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1369, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/src/TurboDiffusion/lib/python3.12/site-packages/torch/nn/modules/module.py", line 928, in _apply
    module._apply(fn)
  File "/src/TurboDiffusion/lib/python3.12/site-packages/torch/nn/modules/module.py", line 955, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/src/TurboDiffusion/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1355, in convert
    return t.to(
           ^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.96 GiB. GPU 0 has a total capacity of 23.52 GiB of which 1.87 GiB is free. Including non-PyTorch memory, this process has 21.61 GiB memory in use. Of the allocated memory 21.16 GiB is allocated by PyTorch, and 11.05 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

I'm running with `torch==2.8.0` with `cu128`, this is totally unexpected as the paper mentioned that 4090 is a tested card.

**Comment by whx1003** [comment]
Thanks for your feedback! The issue has been fixed in the latest code. Could you please try again to figure out if the problem is resolved :)

BTW, I noticed that you’re running inference with the I2V model. Based on our tests, inference with the 14B model requires slightly more than 24GB of VRAM. You can try setting `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True` to reduce the amount of memory reserved by PyTorch. This can help run 14B inference on an RTX4090, although it may result in slightly slower performance.
